# Generated by Django 2.0.5 on 2018-06-21 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import f2kens.apiModel
import f2kens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField()),
                ('motivo_docente', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('En Espera', 'En Espera'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='EnEspera', max_length=50)),
            ],
            options={
                'verbose_name': 'F2',
                'verbose_name_plural': 'F2es',
            },
        ),
        migrations.CreateModel(
            name='Formulario3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField()),
                ('motivo_alumno', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'F3',
                'verbose_name_plural': 'F3es',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', f2kens.apiModel.ApiField(class_=f2kens.models.ApiParent, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', f2kens.apiModel.ApiField(class_=f2kens.models.ApiPreceptor, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formulario3',
            name='preceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f2kens.Preceptor'),
        ),
        migrations.AddField(
            model_name='formulario2',
            name='preceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='f2kens.Preceptor'),
        ),
        migrations.AddField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2kens.Parent'),
        ),
    ]
