# Generated by Django 2.0.6 on 2018-06-12 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Formulario2',
                'verbose_name_plural': 'Formularios2',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formulario2',
            name='preceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2kens.Preceptor'),
        ),
        migrations.AddField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f2kens.Parent'),
        ),
    ]
