# Generated by Django 2.0.6 on 2018-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2kens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario2',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
