# Generated by Django 2.0.6 on 2018-06-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2kens', '0002_auto_20180612_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario2',
            name='state',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default=('En espera', 'En espera'), max_length=30, verbose_name='Estado'),
        ),
    ]
